server:
  messages:
    processing_time: 30 # seconds
    failure_limit: 3
  port: 8088

kafka:
  url: localhost:2181
  topics:
    inbound: myinboundtopic
    outbound:
      success: myoutboundsuccesstopic 
      error: myoutbounderrortopic
      dead: mydeadlettertopic