export ME_TOPICS_INBOUND=myinboundtopic
export ME_TOPICS_OUTBOUND_SUCCESS=myoutboundsuccesstopic
export ME_TOPICS_OUTBOUND_ERROR=myoutbounderrortopic
export ME_MESSAGE_PROC_TIME=30
export ME_MESSAGE_FAILURE_LIMIT=3
export ME_KAFKA_URL=localhost:2181
